name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Debug File Permissions
        run: |
          whoami
          ls -l gradlew
          file gradlew
      - name: Grant execute permission for gradlew
        run:  chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew :blog-java:bake    
        
      - name: Deploy to gh-pages
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin gh-pages